app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/app/Constants.java, app/src/main/java/crux/bphc/cms/CourseDetailActivity.java, app/src/main/java/crux/bphc/cms/DeepLinkActivity.java, app/src/main/java/crux/bphc/cms/LoginActivity.java, app/src/main/java/crux/bphc/cms/MainActivity.java, app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.java, app/src/main/java/crux/bphc/cms/service/DeviceBootReceiver.java, app/src/main/java/crux/bphc/cms/service/NetworkStateReceiver.java, app/src/main/java/crux/bphc/cms/service/NotificationService.java, app/src/main/java/helper/UserAccount.java, app/src/main/java/set/Module.java
Dynamic links implemented- opens normal courses url in app, 
and notifications implemented which checking for new course content every hour or so and sends a notification
=> Dynamic links And Notifications

app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.java
Now the recyclerView's adapter refereshes the data and the Toast message displays at the last iteration of the loop inside the onResponse method
=> Fix a bug while refreshing course content

app/src/main/java/crux/bphc/cms/service/NotificationService.java
=> Fixes #47: ClassCastException while casting SpannableString to String

app/src/main/java/crux/bphc/cms/LoginActivity.java, app/src/main/java/crux/bphc/cms/TokenActivity.java, app/src/main/java/crux/bphc/cms/service/NotificationService.java, app/src/main/java/helper/CourseRequestHandler.java
This happens in two scenarios:
-When network redirects to network login page
-When a user provides additional token instead of first token
=> Fixes #37: JsonsSyntaxException in Courserequesthandler.getcourselist

app/src/main/java/crux/bphc/cms/service/NotificationService.java, app/src/main/java/helper/UserAccount.java
=> Fixes #67: Bug while grouping notifications

app/build.gradle
Updates versionCode to 9 and version code to v1.5.0-beta for beta release.
=> Dark Mode beta release

CHANGELOG.md, app/src/main/java/crux/bphc/cms/MainActivity.java
The selected item in the nav bar didn't update when moving from some views
to the main view by pressing the system back button.
Close #102
Co-authored-by: Prasoon Baghel <prasoon040999@gmail.com>
=> Update selected item in nav bar when back button is pressed

CHANGELOG.md, app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.java, app/src/main/res/layout/fragment_discussion.xml, app/src/main/res/layout/row_attachment_detail_forum.xml
Once an attachment has been downloaded, an elipsis is shown, which
shows the following options:
1. View
2. Re-download
3. Share
Close #99
=> Add ellipsis with more functions for attachments in forum discussions

CHANGELOG.md, app/src/main/java/crux/bphc/cms/MainActivity.java
Pressing the back button is more intuitive, improving UX.
Close: #114
=> Back button on MainActivity intuitive and straightforward

build.gradle, gradle/wrapper/gradle-wrapper.properties
Upgrade Gradle from v5.1.1 to v5.4.1
Upgrade Android Gradle plugin from v3.4.2 to v3.5.0
=> Upgrade Gradle to v5.4.1 and Android Gradle Plugin to v3.5.0

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/app/Constants.java, app/src/main/java/crux/bphc/cms/TokenActivity.java, app/src/main/res/layout/activity_token.xml
Use the endpoint provided by the Moodle Mobile Services plugin. Moodle
does the authentication and verification and, using a magnet URI and
intent filters, redirects the user back to the app.
=> Add Google Login

CHANGELOG.md, app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.java, app/src/main/java/crux/bphc/cms/fragments/FolderModuleFragment.java, app/src/main/java/helper/ModulesAdapter.java, app/src/main/java/helper/MyFileManager.java, app/src/main/java/helper/Util.java, app/src/main/java/set/forum/Attachment.java
Module content and discussion attachements come with metadata like the
file size and last modified epoch. Such information maybe relavant to a
user.
An AlertDialog is used to show the file size and the last modified
properties of a file. Both are shown in a easy-to-read way without
hindering UX.
Close #142
=> AlertDialog to view File properties

app/src/main/java/app/Constants.java, app/src/main/java/app/MyApplication.java, app/src/main/java/crux/bphc/cms/TokenActivity.java, app/src/main/java/helper/Util.java, build.gradle, gradle/wrapper/gradle-wrapper.properties
=> Fix bugs related to invalid tokens during Google Login

app/src/main/java/crux/bphc/cms/fragments/ForumFragment.java, app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.java, app/src/main/java/crux/bphc/cms/fragments/SearchCourseFragment.java, app/src/main/java/crux/bphc/cms/fragments/SettingsFragment.java
The action bar now displays the title of the fragment opened instead of a common title for all fragments
Close #170
=> Change title in action bar for each fragment

app/build.gradle
This PR removes unwanted dependencies:
* AndroidX Browser
* AndroidX Legacy Support Library
* Android CardView Library
* Android Constraint Layout
=> Dependency cleanup

app/build.gradle, app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.java, app/src/main/java/crux/bphc/cms/fragments/ForumFragment.java, app/src/main/java/helper/ModulesAdapter.java, build.gradle
The following depedencies haved updated:
* JUnit to 4.13
* Retrofit to 2.8.1
* Okhttp Logging Intercetpr to 4.5.0
* ButterKnife to 10.2.1
* Picasso to 2.71828
* Realm to 6.1.0
=> Bump version depedencies

app/src/main/java/crux/bphc/cms/fragments/ForumFragment.java, app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.java, app/src/main/java/set/Course.java, app/src/main/res/drawable/pin.xml, app/src/main/res/layout/fragment_course_enrol.xml, app/src/main/res/layout/fragment_discussion.xml, app/src/main/res/layout/fragment_forum.xml, app/src/main/res/layout/fragment_my_courses.xml, app/src/main/res/layout/fragment_search_course.xml, app/src/main/res/layout/row_course.xml, app/src/main/res/layout/row_forum.xml, app/src/main/res/layout/row_search_course.xml
Adjusted whitespaces and fonts, split course names in 'My Courses' fragment into two lines, and enhanced the search bars. Removed 'Download Course' button from row course and added ellipses. These ellipses should open up a menu with options Download Course and Mark all as read.
=> UI changes to fragments

app/src/main/res/layout/row_folder_module_file.xml
Added card view for files in folder module fragment to match the UI theme of the app.
=> UI change to folder module fragment

app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.java, app/src/main/res/layout/row_course.xml
A bottom sheet fragment containing options "Download Course" and "Mark all as read" is displayed on clicking on the ellipses with the course name.
=> Add bottom sheet to ellipsis of MyCourse Fragments

app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.java, app/src/main/res/layout/fragment_my_courses.xml
The search bar on top of my courses fragment does not filter courses in MyCourses based on a parameter. It rather helps the user to search for a particular course from MyCourses.
Hence, replaced the "Filter my courses" hint in the edit text with "Search my courses". 
Also, replaced the filter icon with a magnifying glass icon
=> Replace "filter" with "search" in my courses search bar

app/src/main/java/crux/bphc/cms/models/Course.java
=> Fix regex used to split course name

app/src/main/java/crux/bphc/cms/activities/MainActivity.java, app/src/main/java/crux/bphc/cms/helper/Util.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/nav_header_main.xml, app/src/main/res/menu/activity_main_drawer.xml
* Increased padding for the icons in the menu. 
* Converted the displayed name to TitleCase and removed the domain from the displayed username.
* Removed headers from groups and re-grouped menu items.
* Increased width of the drawer following the Material Design Guidelines. Followed [this](https://android.jlelse.eu/navigation-drawer-styling-under-material-design-f0767882e692) to set drawer width at 320dp.
=> UI changes navigation drawer

app/src/main/java/crux/bphc/cms/helper/MyFileManager.java
Android 10 made changes to permissions regarding file I/O. Many methods
were deperecated and certain functions were limited. Specifically,
listing files in a directory became illegal.
When a user opened up a course, the app would try to list the files in
the course's directory to see what files have been downloaded. However,
`File.list()` would return `null` causing an NPE.
This commit uses the `MediaStore` API to list files in the `Downloads`
folder. `MediaStore.Downloads` was introduced in Android Q had hence
could not be used for previous Android verions. :/
This commit also refactors some parts of the `MyFileManager` class. Expect
further commits meant to cleanup the rest of the class, including
removal of any deprecated method calls.
Closes #208
=> Fix Android Q NPE due to I/O error when opening course

app/build.gradle, app/src/main/java/crux/bphc/cms/activities/MainActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/values/strings.xml
This commit adds the version name and the commit hash in the
MainActivity navigation drawer. The commit hash is found by doing a
`git rev-parse HEAD` during buildtime.
Close #216
=> Add version name and commit hash to app UI

app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.java, app/src/main/java/crux/bphc/cms/helper/FileManager.java
Fixed regression introduced in bb3d563e895bd0cbff4f5a32c98afc91010ac262
=> Fix: UI properly updates after file finishes downloading

app/src/main/res/layout/fragment_discussion.xml, app/src/main/res/layout/row_course_module.xml, app/src/main/res/layout/row_forum.xml
=> Fix: Long module and discussion names get clipped

app/src/main/java/crux/bphc/cms/fragments/CourseEnrolFragment.java
=> Fix: Use MaterialAlertDialogBuilder in CourseEnrolFragment

app/src/main/java/crux/bphc/cms/activities/MainActivity.kt
=> Fix: Bottom Nav Bar not updating when pressing back button

app/src/main/java/crux/bphc/cms/activities/MainActivity.kt, app/src/main/java/crux/bphc/cms/fragments/SearchCourseForEnrolFragment.java, app/src/main/res/drawable/ic_clipboard.xml, app/src/main/res/layout/fragment_search_course.xml, app/src/main/res/menu/bottom_navigation_menu.xml, app/src/main/res/values/strings.xml
Course Enrolment involves searching for a course from all available
courses followed by enrolment. The icon in the bottom naviation was that
of search icon with text of 'Search Course'. The icon did not imply the
ability to enrol to courses.
This patch fixes the aforementioned navigational issue and renames
`SearchCourseFragment` to `SearchCourseFragmentForEnrolFragment`, which
is more appropriate.
=> Refactor Course Enrol code flow

app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.java, app/src/main/java/crux/bphc/cms/fragments/ForumFragment.java, app/src/main/java/crux/bphc/cms/models/NotificationSet.kt, app/src/main/java/crux/bphc/cms/models/forum/Discussion.kt
Fix: Unparsed HTML tags in Discussion notifications
Close #261
=> Fix: Unparsed HTML tags in Discussion notifications

CHANGELOG.md, app/src/main/java/crux/bphc/cms/fragments/CourseContentFragment.java
=> Fix: Unimplemented module types launch in browser

CHANGELOG.md, app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.kt
=> Fix: Mark as favorite updates UI

app/src/main/java/crux/bphc/cms/activities/CourseDetailActivity.kt, app/src/main/java/crux/bphc/cms/activities/InfoActivity.java, app/src/main/java/crux/bphc/cms/activities/MainActivity.kt, app/src/main/java/crux/bphc/cms/activities/TokenActivity.kt, app/src/main/java/crux/bphc/cms/app/MyApplication.java, app/src/main/java/crux/bphc/cms/fragments/CourseContentFragment.kt, app/src/main/java/crux/bphc/cms/fragments/PreferencesFragment.kt, app/src/main/java/crux/bphc/cms/models/UserAccount.kt, app/src/main/java/crux/bphc/cms/widgets/PropertiesAlertDialog.java
=> Make dark mode the default

CHANGELOG.md, app/src/main/java/crux/bphc/cms/activities/MainActivity.kt, app/src/main/java/crux/bphc/cms/activities/TokenActivity.kt, app/src/main/java/crux/bphc/cms/fragments/CourseContentFragment.kt, app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.kt, app/src/main/java/crux/bphc/cms/fragments/ForumFragment.kt, app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.kt, app/src/main/java/crux/bphc/cms/helper/CourseDataHandler.java, app/src/main/java/crux/bphc/cms/helper/CourseDownloader.java, app/src/main/java/crux/bphc/cms/helper/CourseRequestHandler.java
Went ahead and cleaned up the API for CourseDataHandler and
CourseRequestHandler. Both those functions need to be Kotlinified and
relavant functions need to be converted to suspendables.
=> Cleanup: Coroutines when syncing from MyCoursesFragment

CHANGELOG.md, app/src/main/java/crux/bphc/cms/activities/CourseDetailActivity.kt, app/src/main/java/crux/bphc/cms/app/Constants.kt, app/src/main/java/crux/bphc/cms/fragments/SearchCourseForEnrolFragment.java
Regression from (possibly) `dc41cf`.
=> Fix: Pressing course name in SearchCourseForEnrolFragment does nothing

app/src/main/res/layout/fragment_discussion.xml
The constraints weren't properly defined. Further more, the lack of a
scrollview meant if the title and/or text got too big, the attachment
section would no longer be visible.
Close #303
=> Fix improper layout constraint and added scrollview

app/src/main/java/crux/bphc/cms/activities/CourseDetailActivity.kt
=> Fix: NPE when opening notification for course not available locally

CHANGELOG.md, app/src/main/java/crux/bphc/cms/activities/CourseDetailActivity.kt, app/src/main/res/values/strings.xml
Regression from b4a7710d49f684ae2d0fe44d0a52c4e98dbae469.
Close #310
=> Fix: App crash when attempting to enrol to course

app/src/main/java/crux/bphc/cms/fragments/CourseContentFragment.kt
=> Fix: Show refresh indicator on opening notification

app/src/main/java/crux/bphc/cms/app/Urls.kt, app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.kt, app/src/main/java/crux/bphc/cms/fragments/ForumFragment.kt
=> Fix: Profile Pictures Not Being Fetched Properly

CHANGELOG.md, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/crux/bphc/cms/activities/TokenActivity.kt, app/src/main/java/crux/bphc/cms/activities/TokenViewModel.kt, app/src/main/java/crux/bphc/cms/models/SingleLiveEvent.kt, app/src/main/java/crux/bphc/cms/viewmodels/TokenViewModel.kt, app/src/main/res/layout/activity_token.xml, app/src/main/res/values/strings.xml
All of TokenActivity's business logic has been shifted to a ViewModel. Its usage of AsyncTask has been shifted to use Coroutines, LiveData, and Observers. Moreover, the usage of deprecated ProgressDialog has also been switched to a simple ProgressBar and accompanying text on the screen.
=> Shifted TokenActivity to use a ViewModel and switched its usage of ProgressDialog

CHANGELOG.md, app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/crux/bphc/cms/activities/MainActivity.kt, app/src/main/java/crux/bphc/cms/adapters/FilesAdapter.kt, app/src/main/java/crux/bphc/cms/background/MigrateDataWorker.kt, app/src/main/java/crux/bphc/cms/core/FileExtensions.kt, app/src/main/java/crux/bphc/cms/core/FileManager.kt, app/src/main/java/crux/bphc/cms/fragments/FilesFragment.kt, app/src/main/java/crux/bphc/cms/fragments/FolderModuleFragment.kt, app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.kt, app/src/main/java/crux/bphc/cms/models/Download.kt, app/src/main/java/crux/bphc/cms/models/UserAccount.kt, app/src/main/java/crux/bphc/cms/utils/FileUtils.kt, app/src/main/java/crux/bphc/cms/viewmodels/FilesViewModel.kt, app/src/main/res/drawable/ic_document_unknown_type.xml, app/src/main/res/drawable/outline_delete_24.xml, app/src/main/res/drawable/outline_favorite_24.xml, app/src/main/res/drawable/outline_favorite_border_24.xml, app/src/main/res/drawable/outline_file_download_24.xml, app/src/main/res/drawable/outline_folder_24.xml, app/src/main/res/layout/downloads_fragment.xml, app/src/main/res/layout/row_download.xml, app/src/main/res/menu/bottom_navigation_menu.xml, app/src/main/res/values/strings.xml
* Switched the default downloads location to be app specific external media storage.
* Added a worker to migrate the user's old data from the Downloads folder to the app specific external media storage.
* Added a new files screen to let users view and delete downloaded course content.
=> Migrate to scoped storage and add a file manager

app/src/main/java/crux/bphc/cms/fragments/ForumFragment.kt, app/src/main/res/values/strings.xml
=> Fix blank screen on no announcements.

app/src/main/java/crux/bphc/cms/fragments/FilesFragment.kt, app/src/main/res/values/styles.xml
Now dialog message is as shown below:
=> Fix cancel button not visible in dark mode.

app/build.gradle, app/src/main/AndroidManifest.xml, app/src/main/java/crux/bphc/cms/activities/CourseDetailActivity.kt, app/src/main/java/crux/bphc/cms/activities/MainActivity.kt, app/src/main/java/crux/bphc/cms/fragments/CourseContentFragment.kt, app/src/main/java/crux/bphc/cms/fragments/CourseEnrolFragment.kt, app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.kt, app/src/main/java/crux/bphc/cms/fragments/FilesFragment.kt, app/src/main/java/crux/bphc/cms/fragments/FolderModuleFragment.kt, app/src/main/java/crux/bphc/cms/fragments/ForumFragment.kt, app/src/main/java/crux/bphc/cms/fragments/InfoFragment.kt, app/src/main/java/crux/bphc/cms/fragments/MoreFragment.kt, app/src/main/java/crux/bphc/cms/fragments/MoreOptionsFragment.kt, app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.kt, app/src/main/java/crux/bphc/cms/fragments/PreferencesFragment.kt, app/src/main/java/crux/bphc/cms/fragments/SearchCourseForEnrolFragment.kt, app/src/main/res/values/attrs.xml, build.gradle
compileSdkVersion was bumped since the newer versions of the libraries had a higher compileSdkVersion of 33
=> Bumped app dependencies and migrated code to use View Binding

app/src/main/java/crux/bphc/cms/activities/MainActivity.kt
As of Android 13, apps will have to request permission to send notifications, and already have access to files in their app-specific directory on external storage
=> Update requested permissions to interact with storage and send notifications

app/src/main/java/crux/bphc/cms/models/course/Course.kt, app/src/main/java/crux/bphc/cms/utils/FileUtils.kt, app/src/main/res/layout/row_attachment_detail_forum.xml
- Use fullNames instead of shortNames
- Add pptx mimeType to render PPT drawable for pptx files
- Remove bottom constraint for ImageView in forum attachment row
=> Miscellaneous minor bug fixes
