crux-bphc/CMS-Android

.gitignore
app/build.gradle
app/src/main/java/app/MyApplication.java
app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java
app/src/main/java/helper/APIClient.java
app/src/main/java/helper/MoodleServices.java
build.gradle
gradle/wrapper/gradle-wrapper.properties

1. Replaces "compile" with "implementation"
2. Adds Java 8 support
3. Adds ButterKnife library for resources injection
4. Adds OkHttp3-Logging Interceptor for easy debugging of network calls.
5. Adds a APIClient class for centralizing retrofit instance generation.

Updates gradle for AndroidStudio3.0.1

---

app/src/main/java/crux/bphc/cms/service/NotificationService.java

Intent of Notification's flags have been changed such that it's top stack is cleared before the activity gets launched
On clicking notification leads to TokenActivity rather than LoginActivity

Fixes #19: Clicking on notification launches a new task.

---

app/src/main/java/crux/bphc/cms/MainActivity.java
app/src/main/java/crux/bphc/cms/service/NotificationService.java
app/src/main/java/helper/ModulesAdapter.java

Changes made in the PR:
1. Added a condition that shows the summary notifications for post nougat devices. Earlier the summary notification in pre nougat devices showed a blank notification. This change ensures that they show only the individual notifications
2. Assigned a new channel for the bundle notifications and set it's importance to default and changed the individual updates channel's priority to low. This ensures that a single sound is a made for each bundle i.e each course
3. Added a break statement in one of the switch statements in ModulesAdapter

Support showing individual notifs for lower APIs

---

app/src/main/java/crux/bphc/cms/service/NotificationService.java
app/src/main/java/set/NotificationSet.java

Changes made in the PR:
1. The course name for the notification is added as it's summary
2. The section name is it's title and the module name is it's context
For lower API devices it remains the same

Change notifications title and add summary

---

app/src/main/java/crux/bphc/cms/TokenActivity.java

Hello, before launching new activity, we check if a ProgressDialog is displayed, then dismiss it.

Fix ProgressDialog leak.

---

app/src/main/java/crux/bphc/cms/TokenActivity.java

If the user has already logged in (i.e provided token) then the app
crashes since a ProgressDialog would'nt have been instantiated yet but
would still be dismissed.

Null pointer exception in TokenActivity.onCreate()

---

CHANGELOG.md

This was missed and should have been included in the `dark_theme` branch PR.

Update Changelog to include dark theme

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/fragments/ForumFragment.java

Notifications for very old announcements were being created. 
If a user goes to a Forum fragment, this results in the latest 20 discussions in that forum to be fetched and saved in Realm. The next time the Notification job runs, all of the discussions would be fetched and compared against the discussions cached locally. If total number of discussions is greater than 20 then the very old discussions would be treated as new since they would not be in the local cache and notifications would be issued for them.
Close #98

Fix Notification Spam

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java
app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.java
app/src/main/java/crux/bphc/cms/fragments/ForumFragment.java
app/src/main/java/helper/HtmlTextView.java
app/src/main/java/helper/Util.java
app/src/main/res/layout/row_course_section.xml

Hyperlinks in CoureSections and Discussions weren't being rendered properly
CourseSection descriptions are HTML strings with anchor tags to mark links.
However, insertion of the "Show More" span removes the URLSpan created from
the original HTML string by converting the spanned string to a plain string.
This commit ensures that the "Show More" span is added along with the URLSpan
instead of overwriting the URLSpan.
Discussions didn't have support for hyperlinks
Close #92

Hyperlinks are rendered properly

---

app/src/main/java/crux/bphc/cms/SettingsActivity.java
app/src/main/java/crux/bphc/cms/service/NotificationService.java

After the theme has been changed from the settings menu and the software
back button is pressed, the theme wouldn't update properly.
The theme is applied while an activity is created. However, the software back
button doesn't recreate the previous activity, it just resumes it. This commit
makes sure that the activity is re-created only if required. If there is no
theme change, the previous activity will be resumed.
Sequence of creation of the NotificationService has been modified to allow for
early exit if need be.
Close: #111

Back button from SettingsActivity applies theme

---

app/src/main/java/helper/ModulesAdapter.java
app/src/main/res/layout/row_course_module_resource.xml

The name of the modules had no default actions attached to them.
The default action associated with the module like downloading or
viewing will take place when a user clicks the name of the module or
the download icon.
Close #122

Modules names are clickable

---

README.md

A Postman collection would be beneficial to newcomers, newbies and
advanced developers alike. Rather than having to go through the source
code to understand the API calls being made (and trying to execute it
themselves), they can just use the Postman collection provided.
close #134

Create and link Postman collection in README.md

---

app/src/main/AndroidManifest.xml
app/src/main/java/crux/bphc/cms/CourseModulesActivity.java
app/src/main/java/crux/bphc/cms/MainActivity.java
app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java
app/src/main/java/helper/ModulesAdapter.java

One can now share a link using any text message app and that link can be opened by the receiving user using the app which will open the file in the browser using the receiving user's
token. If they are not enrolled in the course of which the shared module is a part,
they are shown a Toast which says that they need to enroll in this course in order to
view that file.
close #137

Issue #137: Added the ability to share modules without having to download them

---

app/src/main/java/crux/bphc/cms/fragments/ForumFragment.java

While changing fragments while ForumFragment is refreshing calls the function OnDetach() before the network request is still processing making getContext() return null causing the NullPointerException. Added a global context variable initialised in OnCreate().

Fixes #84 - NullPointerException at ForumFragment.onFailure()

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/fragments/FolderModuleFragment.java
app/src/main/java/helper/ModulesAdapter.java
app/src/main/java/helper/MyFileManager.java
app/src/main/java/set/Module.java
app/src/main/res/layout/fragment_folder_module.xml
app/src/main/res/layout/row_folder_module_file.xml

Folder modules are a frequent occurence on CMS, which the app did not
have support for.
Folder modules are essentially a folder of files. Earlier, the app would
download all files inside a folder and would open up the first file of
that folder.
The fragment allows for the listing of all files inside the folder
module.
Close #23

Create FolderModuleFragment to support Folder modules

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/service/NotificationService.java
app/src/main/java/set/NotificationSet.java

New discussions in site news weren't notified. This meant that important
site news would go missed by students.
All site news, under the title "Site News" are notified at the same
frequency as the notifications for other course sections, modules and
discussions
Close #113

Site news notification

---

app/src/main/java/set/Course.java

Moodle HTML encodes certain strings which are now decoded before being
set to views.
Close #152

Fix HTML encoding while display strings

---

app/src/main/java/crux/bphc/cms/service/NotificationService.java
app/src/main/java/set/NotificationSet.java

Notifications summaries are no longer ugly, unparsed HTML strings.
Cleaned up the `NotificationSet` class as well.
Close #147

Fix unparsed HTML in notification summary

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/service/NotificationService.java

Probably a Android quirk, but having a null notif summary creates an
empty ghost notification. Not sure if it's documented.
Closes #145

Fix empty ghost site notification

---

app/src/main/java/crux/bphc/cms/TokenActivity.java

Site news is now fetched and cached at login
Earlier, site news was not cached at login which meant the next time the
notification service ran, it would create a notification each site news
dicussion, essentially creating a notification spam.
Fix #146
Also, refactor `TokenActivity`.

Site news is now fetched and cached at login

---

app/src/main/java/crux/bphc/cms/fragments/ForumFragment.java

The action bar for fragment displaying announcements shows the course name as the title now.

Fixed action bar title for announcements

---

app/build.gradle

The following dependencies have been upgraded: 
* AndroidX Preference Fragment (to v1.1.1)
* AndroidX Vectordrawable (to v1.1.0)
* Android Material Theme (to v1.1.0)
* AndroidX App Compat (to v1.1.0)
* Google Play Services (to v18.0.0) 
AndroidX SwipeRefreshLayout had to be added after bumping material theme.

Bump versions of dependencies

---

app/src/main/java/crux/bphc/cms/fragments/MoreOptionsFragment.java
app/src/main/res/layout/fragment_more_options.xml
app/src/main/res/values/styles.xml

Apart from what the title says, this commit also changes the parent of
the `AppTheme` style. BottomSheetDialogFragment being a material class,
a couple of attributes needed to be set in our styles. These are set by
the new parent Material Components theme, removing the need for us to move
these our to our style. The lack of these would cause an InflateException
RTE.
This change also meant that the `onCreateView` inflater context jugaad
that was done in `MoreOptionsFragment` is no longer required. I still
have no clue why that was a problem to be begin with.
Overriding the default BottomSheetDialog themes also means that we don't
have to worry about animations in our code or styles.
This small change has resulted in a massive simplification of
our codebase and styles.

Round More Options BottomSheetDialogFragment corners

---

app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java

Course sections that have no module and no description are now
displayed. Default empty sections like Topic 1, Topic 2, etc are
not displayed.
close #100

Empty course sections are now displayed

---

app/src/main/java/crux/bphc/cms/fragments/CourseSectionFragment.java
app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.java
app/src/main/java/helper/CourseDataHandler.java
app/src/main/java/set/Course.java

The title on the action bar for Course Section fragment is reduced to the course code and section number. For example, BIO F111 L1 instead of BIO F111 GENERAL BIOLOGY L1 that was shown earlier. The long course name on action bar got truncated and did not show the section number.
Also changed the regex used to split the course name.

Change action bar title for Course fragment

---

app/src/main/java/crux/bphc/cms/MainActivity.java
app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.java
app/src/main/java/helper/Util.java
app/src/main/res/values/attrs.xml
app/src/main/res/values/styles.xml

The move to material theme as the parent of `AppTheme` (`1b506ee624`)
meant that `AlertDialog`s buttons were broken. This replaces
AlertDialogs that utilize buttons with a MaterialAlertDialog.

Replace AlertDialog with MaterialAlertDialog and custom theme

---

app/src/main/res/layout/row_course.xml
app/src/main/res/layout/row_forum.xml

Long course names in My course fragment and instructor names in discussion now don't overlap with other children text view.

Fix overlapping text in UI

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/helper/ModulesAdapter.java

Regression in `35484fdc`.
Modules would visually look like read/unread when the more options
ellipsis button is used. However, the internal state (`isNewContent`)
doesn't change.
Closes #196

Fix: Read/Unread Module Visual Bug

---

app/src/main/AndroidManifest.xml
app/src/main/res/layout/row_course.xml

No idea why the lint issues weren't caught when c20c0e4 was pushed. They aren't being caught locally either.

Fix: Lint issues that weren't caught in c20c0e4

---

app/src/main/java/crux/bphc/cms/adapters/delegates/CourseSectionDelegate.java
app/src/main/java/crux/bphc/cms/utils/Utils.java
app/src/main/java/crux/bphc/cms/widgets/CollapsibleTextView.java
app/src/main/res/layout/fragment_discussion.xml
app/src/main/res/layout/row_course_module.xml
app/src/main/res/layout/row_course_section.xml
app/src/main/res/layout/row_forum.xml

TextViews like Course Section descriptions, announcements etc are not
selectable. This will allow users to copy text (including links) which
may otherwise not be clickable (due to non-existent anchor tags).
This commit also introduced a trim function for character sequences to
get rid of leading and trailing CollapsibleTextViews as well as
centering elements in `row_course_module`.

Make dynamic TextViews selectable

---

app/src/main/java/crux/bphc/cms/adapters/delegates/CourseSectionDelegate.java
app/src/main/java/crux/bphc/cms/utils/Utils.java

This patch also checks to see if the summary of a course section is
empty HTML parsing and trimming instead of before. This prevents course
sections with no string from being visible.
Close #242

Fix: App crash when whitespace only string to trimWhiteSpace

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/helper/CourseRequestHandler.java

`resolve()` in keeps calling changeName until a new unique filename
has been set by the `changeName()`. However `changeName()` does nothing to
files that have no extensions or those that have extensions with strings
between paranthesis. This causes an infinte loop.
Close #246

Fix infinite loop in 'resolve()'

---

app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.kt
app/src/main/res/menu/my_courses_menu.xml

Added an options menu in the MyCourses fragment which marks all modules of all sections of all courses as read.
Currently, this process takes a noticeable amount of time with large number of modules. I'm assuming it's the
Realm transactions which need to be done for each module. If possible, this should be made asynchronous so that
UI feels more snappy.

Issue #80 Mark all as Read

---

CHANGELOG.md
app/build.gradle
app/src/main/java/crux/bphc/cms/adapters/delegates/CourseModuleDelegate.java
app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.java
app/src/main/java/crux/bphc/cms/fragments/ForumFragment.java
app/src/main/java/crux/bphc/cms/glide/SvgDecoder.kt
app/src/main/java/crux/bphc/cms/glide/SvgDrawableTranscoder.kt
app/src/main/java/crux/bphc/cms/glide/SvgModule.kt

Neither Glide nor Picasso has builtin support for decoding SVGs and
displaying them in ImagesViews. However, Glide's API allows for
specifying custom decoders. Glide fetches the SVG and delgates through
our pipeline to AndroidSVG for decoding. Glide also handles caching
SVGs. And, most importantly, loading raster images works just like it
used to with Picasso.
Close #127

Switch to Glide from Picasso, fix loading remote SVGs

---

app/src/main/java/crux/bphc/cms/models/course/Module.kt

Modules which had contents (for eg. Resource modules) weren't
downloadable. Bug Introduced in
`8a0a85b1b581906b5fc0f2d762249e4d7399f1e7`

Fix: Downloadable modules no longer downloadable

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.kt

Changed the course list being used to get the title course name, from the 'courses' list of MyCourseFragment class to the 'courses' declared inside the Adapter class. The latter is the list which is sorted and displayed.
Fixes #264

Fix title of more option bottom sheet for courses

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/fragments/CourseContentFragment.java
app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.kt

The UI is updated when a course is marked as read or a module is marked as unread.
Fixes #266

Update UI for mark as read/unread option in bottom sheet

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/app/Constants.java

Moodle was shifted to the cloud. It now sits at
https://cms.bits-hyderabad.ac.in

Update Moodle instance URL

---

app/src/main/AndroidManifest.xml
app/src/main/java/crux/bphc/cms/core/FileManager.kt

Scoped Storage is a shitshow and reduces the functioanlity provided by
the app. It is impossible to list files created by your own app after
reinstalls. The alternative to opting out would be to move to the
external app directory. However, this means users won't be able to find
their files easily through a file manager.
Let's hope Google brings an alternative for our usecase.
Also: This patch also cleans up FileManager

Opt out of Scoped Storage

---

app/src/main/java/crux/bphc/cms/activities/CourseDetailActivity.kt
app/src/main/java/crux/bphc/cms/activities/MainActivity.kt

This prevents from the same intent being resolved each time the user
comes back to the app.

Move intent resolution to onCreate

---

app/src/main/java/crux/bphc/cms/core/PushNotifRegManager.kt
app/src/main/java/crux/bphc/cms/fragments/PreferencesFragment.kt

Registration was happening from whatever scope invoked the function.
Though the impact is not huge, the entire process is meant to happen in
the background, even if called from the main thread.
Also fixed a bug where registration would happen before user is even
logged in.

Change Coroutine scopes during push notif (de)registration

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/activities/TokenActivity.kt
app/src/main/java/crux/bphc/cms/models/UserAccount.kt
app/src/main/java/crux/bphc/cms/models/core/UserDetail.kt

Moodle 3.7+ provides an additional private token for non-admin users
over https. The private token is used to login the user to the website
on a browser from the app. This may become useful later. However this
patch only fixes login.

Fix: SSO Login

---

CHANGELOG.md
app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.kt
app/src/main/java/crux/bphc/cms/models/course/Course.kt

`fullname` property in the API response was not being handled properly.
Considering the entirety of MyCoursesFragment uses `shortname`,
including in the actual course name, we should search `shortname` instead
of `fullname`.

Fix: Searching for courses yields no results

---

app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.kt

Trying to download an attachment immediately after the discussion loads
after a network sync crashes the app (for example downloading an
attachment in discussion after pressing on a notification).
Remove method calls to managed Realm objects since there is no guarantee
that the objects are managed by Realm.
Close #308

Fix: Crash on downloading attachments after network sync of discussion

---

CHANGELOG.md
app/src/main/res/values/styles.xml

Make it the same as the activity background. Also set `isLightTheme`
style attribute for the themes.
Close #315

Fix: Theme of System Navigation Bar

---

.github/workflows/build.yml

We don't use the NDK in the app. Installing the NDK, even if it's from a
cache just slows things down.

Remove NDK cache steps from Actions workflow

---

app/src/main/java/crux/bphc/cms/fragments/CourseContentFragment.kt
app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.kt
app/src/main/java/crux/bphc/cms/helper/CourseDataHandler.java

Use batch updates to mark items as read/unread instead of individual
updating database. This makes the 'Mark all as read' action from
MyCoursesFragment near instantaneous when you everything in every
course as unread.
Also refactored 'markModuleAsReadOrUnread' method.

Improve module read/unread logic

---

app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.kt

Changed the download course function to use the courses list of the Adapter since it is updated after sorting, alphabetically and according to favourite status.
Fixes #331

Use sorted courses list for download course

---

app/src/main/java/crux/bphc/cms/fragments/FilesFragment.kt

Snackbar message is now clearly visible on deletion.
Light mode:
Dark mode:

Fix deletion snackbar visibility issue.

---

app/src/main/java/crux/bphc/cms/activities/MainActivity.kt

Since the requestReadStoragePermission function now also requests for notification permissions, it is more appropriate to use requestPermission for the function instead

Refactor permission request function

---

app/src/main/java/crux/bphc/cms/adapters/delegates/CourseSectionDelegate.kt
app/src/main/java/crux/bphc/cms/fragments/DiscussionFragment.kt
app/src/main/java/crux/bphc/cms/fragments/ForumFragment.kt
app/src/main/java/crux/bphc/cms/models/course/CourseSection.kt
app/src/main/java/crux/bphc/cms/models/course/Module.kt
app/src/main/java/crux/bphc/cms/models/forum/Discussion.kt

This PR fixes HTML text rendering onto course sections and discussions, allowing users to click on any embedded links, if present

Fix HTML Text rendering in course section and discussion

---

app/src/main/java/crux/bphc/cms/fragments/MyCoursesFragment.kt
app/src/main/java/crux/bphc/cms/fragments/NotificationsFragment.kt
app/src/main/java/crux/bphc/cms/helper/CourseDataHandler.java
app/src/main/java/crux/bphc/cms/helper/CourseRequestHandler.java
app/src/main/java/crux/bphc/cms/models/core/Notification.kt
app/src/main/java/crux/bphc/cms/network/MoodleServices.java
app/src/main/res/layout/fragment_notifications.xml
app/src/main/res/layout/row_notification.xml
app/src/main/res/menu/my_courses_menu.xml
app/src/main/res/values/strings.xml

Added a new notifications screen from where users can read notifications, mark certain notifications as read, and go to the website on clicking the notication object

Add a notifications screen for users to access notifications

---

CHANGELOG.md
app/build.gradle

Date for Version 1.10 in CHANGELOG has been updated to 2023-05-23 as 1.10 was released to the Playstore on that date

Bump app version to 1.11 (1110000) in CHANGELOG.md and Gradle
